services:
  backend:
    build:
      context: .
    container_name: fastapi-backend
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./output:/sync_space/output
    user: "${UID:-1000}:${GID:-1000}"
    restart: always

  frontend:
    build:
      context: .
    container_name: streamlit-frontend
    command: streamlit run main.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./output:/sync_space/output
    user: "${UID:-1000}:${GID:-1000}"
    depends_on:
      - backend
    restart: always

volumes:
  shared_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./output